import { useEffect, useState } from 'react';
import { apiClient, type Config } from '../api/client';
import FormField from './FormField';

interface ConfigModalProps {
  config: Config | null;
  onClose: () => void;
  onSave: (configId?: string) => void;
  saveButtonText?: string;
}

// Helper function to extract domain from URL
function extractDomain(url: string): string | null {
  try {
    const urlObj = new URL(url);
    return urlObj.hostname.replace(/^www\./, '');
  } catch {
    return null;
  }
}

// Generate ID from domain (e.g., example.com -> example_com)
function generateIdFromDomain(domain: string): string {
  return domain.replace(/\./g, '_').replace(/[^a-z0-9_]/gi, '_').toLowerCase();
}

// Generate name from domain (e.g., example.com -> Example.com Check)
function generateNameFromDomain(domain: string): string {
  // Capitalize first letter of domain
  const capitalized = domain.charAt(0).toUpperCase() + domain.slice(1);
  return `${capitalized} Check`;
}

// Generate unique ID by checking existing configs
async function generateUniqueId(baseId: string): Promise<string> {
  try {
    const existingConfigs = await apiClient.listConfigs();
    const existingIds = new Set(existingConfigs.map(c => c.id));
    
    if (!existingIds.has(baseId)) {
      return baseId;
    }
    
    // If ID exists, append number
    let counter = 1;
    let uniqueId = `${baseId}_${counter}`;
    while (existingIds.has(uniqueId)) {
      counter++;
      uniqueId = `${baseId}_${counter}`;
    }
    return uniqueId;
  } catch {
    // If we can't check, just return base ID
    return baseId;
  }
}

export default function ConfigModal({
  config,
  onClose,
  onSave,
  saveButtonText = 'Save',
}: ConfigModalProps) {
  // Initialize with empty values
  const [formData, setFormData] = useState<Partial<Config>>({
    id: '',
    name: '',
    start_url: '',
    timeout: 15,
    delay: 0.5,
    max_depth: null,
    show_skipped_links: false,
    whitelist_codes: [],
    domain_rules: {},
  });
  
  // Local state for form inputs
  const [whitelistCodesInput, setWhitelistCodesInput] = useState<string>('');
  const [domainRulesInput, setDomainRulesInput] = useState<string>('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [autoGeneratedId, setAutoGeneratedId] = useState(false);
  const [autoGeneratedName, setAutoGeneratedName] = useState(false);

  // Update form inputs when config changes (including initial mount)
  useEffect(() => {
    if (config) {
      // Editing existing config
      setFormData(config);
      setWhitelistCodesInput(config.whitelist_codes?.join(', ') || '');
      setDomainRulesInput(config.domain_rules ? JSON.stringify(config.domain_rules, null, 2) : '');
      setAutoGeneratedId(false);
      setAutoGeneratedName(false);
    } else {
      // Creating new config
      setFormData({
        id: '',
        name: '',
        start_url: '',
        timeout: 15,
        delay: 0.5,
        max_depth: null,
        show_skipped_links: false,
        whitelist_codes: [],
        domain_rules: {},
      });
      setWhitelistCodesInput('');
      setDomainRulesInput('');
      setAutoGeneratedId(false);
      setAutoGeneratedName(false);
    }
  }, [config]);

  // Auto-generate ID and name from start_url when creating new config
  useEffect(() => {
    if (!config && formData.start_url) {
      const domain = extractDomain(formData.start_url);
      if (domain) {
        // Auto-generate ID if empty or was auto-generated
        if (autoGeneratedId || !formData.id) {
          const baseId = generateIdFromDomain(domain);
          generateUniqueId(baseId).then(uniqueId => {
            setFormData(prev => ({ ...prev, id: uniqueId }));
            setAutoGeneratedId(true);
          });
        }
        
        // Auto-generate name if empty or was auto-generated
        if (autoGeneratedName || !formData.name) {
          const generatedName = generateNameFromDomain(domain);
          setFormData(prev => ({ ...prev, name: generatedName }));
          setAutoGeneratedName(true);
        }
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [formData.start_url, config]);

  // Reset auto-generated flag when user manually edits name
  const handleNameChange = (value: string | number) => {
    setFormData({ ...formData, name: value as string });
    setAutoGeneratedName(false);
  };

  // Handle Escape key to close modal
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    document.addEventListener('keydown', handleEscape);
    return () => {
      document.removeEventListener('keydown', handleEscape);
    };
  }, [onClose]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setError(null);

    try {
      // Parse whitelist_codes from comma-separated string
      const whitelistCodes = whitelistCodesInput
        .split(',')
        .map((code) => parseInt(code.trim()))
        .filter((code) => !isNaN(code));

      // Parse domain_rules from JSON string
      let domainRules = {};
      if (domainRulesInput.trim()) {
        try {
          domainRules = JSON.parse(domainRulesInput);
        } catch {
          throw new Error('Invalid JSON format for domain rules');
        }
      }

      // For new configs, ensure we have ID and name
      let finalConfigData = { ...formData };
      
      if (!config) {
        // Generate ID and name if not set
        if (!finalConfigData.id && formData.start_url) {
          const domain = extractDomain(formData.start_url);
          if (domain) {
            const baseId = generateIdFromDomain(domain);
            finalConfigData.id = await generateUniqueId(baseId);
          } else {
            throw new Error('Invalid URL. Cannot generate ID from URL.');
          }
        }
        
        if (!finalConfigData.name && formData.start_url) {
          const domain = extractDomain(formData.start_url);
          if (domain) {
            finalConfigData.name = generateNameFromDomain(domain);
          } else {
            throw new Error('Invalid URL. Cannot generate name from URL.');
          }
        }
        
        if (!finalConfigData.id) {
          throw new Error('Config ID is required');
        }
        
        if (!finalConfigData.name) {
          throw new Error('Config name is required');
        }
      }

      const configData = {
        ...finalConfigData,
        whitelist_codes: whitelistCodes,
        domain_rules: domainRules,
      };

      if (config) {
        // Update existing
        await apiClient.updateConfig(config.id, configData);
        onSave(config.id);
      } else {
        // Create new - check uniqueness one more time
        const uniqueId = await generateUniqueId(configData.id as string);
        configData.id = uniqueId;
        const createdConfig = await apiClient.createConfig(configData as Config);
        onSave(createdConfig.id);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save configuration');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/30 backdrop-blur-sm flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg shadow-2xl max-w-2xl w-full max-h-[90vh] flex flex-col">
        <form onSubmit={handleSubmit} className="flex flex-col h-full overflow-hidden">
          <div className="p-6 space-y-4 overflow-y-auto flex-1">
            <h3 className="text-lg font-medium text-gray-900">
              {config ? 'Edit Configuration' : 'New Configuration'}
            </h3>

            {error && (
              <div className="rounded-md bg-red-50 p-4">
                <p className="text-sm text-red-700">{error}</p>
              </div>
            )}

            <FormField
              label="Start URL"
              type="url"
              value={formData.start_url || ''}
              onChange={(value) => setFormData({ ...formData, start_url: value as string })}
              required
              placeholder="https://example.com"
            />

            <div>
              <label className="block text-sm font-medium text-gray-700">
                ID
              </label>
              <div className="mt-1 block w-full rounded-md border-gray-300 shadow-sm bg-gray-50 sm:text-sm px-3 py-2 text-gray-600">
                {formData.id || (config ? config.id : 'Auto-generated from URL')}
              </div>
              <p className="mt-1 text-xs text-gray-500">
                Automatically generated from URL
              </p>
            </div>

            <FormField
              label="Name"
              type="text"
              value={formData.name || ''}
              onChange={handleNameChange}
              placeholder={config ? undefined : 'Auto-generated from domain'}
            />

            <div className="grid grid-cols-2 gap-4">
              <FormField
                label="Timeout (seconds)"
                type="number"
                value={formData.timeout || 15}
                onChange={(value) => setFormData({ ...formData, timeout: value as number })}
                min="1"
              />

              <FormField
                label="Delay (seconds)"
                type="number"
                value={formData.delay || 0.5}
                onChange={(value) => setFormData({ ...formData, delay: value as number })}
                min="0"
                step="0.1"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Max Depth
              </label>
              <input
                type="number"
                value={formData.max_depth === null ? '' : formData.max_depth}
                onChange={(e) =>
                  setFormData({
                    ...formData,
                    max_depth: e.target.value === '' ? null : parseInt(e.target.value),
                  })
                }
                placeholder="∞ (unlimited)"
                min="1"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2"
              />
              <p className="mt-1 text-xs text-gray-500">
                Leave empty for unlimited depth
              </p>
            </div>

            <div>
              <label className="flex items-center space-x-2">
                <input
                  type="checkbox"
                  checked={formData.show_skipped_links || false}
                  onChange={(e) =>
                    setFormData({ ...formData, show_skipped_links: e.target.checked })
                  }
                  className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                />
                <span className="text-sm font-medium text-gray-700">
                  Show Skipped Links
                </span>
              </label>
              <p className="mt-1 text-xs text-gray-500 ml-6">
                Include skipped links in the report
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Whitelist Codes
              </label>
              <input
                type="text"
                value={whitelistCodesInput}
                onChange={(e) => setWhitelistCodesInput(e.target.value)}
                placeholder="e.g., 403, 999"
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2"
              />
              <p className="mt-1 text-xs text-gray-500">
                Comma-separated HTTP status codes to treat as valid (e.g., 403, 999)
              </p>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700">
                Domain Rules (JSON)
              </label>
              <textarea
                value={domainRulesInput}
                onChange={(e) => setDomainRulesInput(e.target.value)}
                placeholder={'{\n  "linkedin.com": {\n    "allowed_codes": [999, 429],\n    "description": "LinkedIn rate limiting (optional)"\n  }\n}'}
                rows={8}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-3 py-2 font-mono text-xs"
              />
              <p className="mt-1 text-xs text-gray-500">
                Domain-specific rules in JSON format. Field 'description' is optional.
              </p>
            </div>
          </div>

          <div className="bg-gray-50 px-6 py-3 flex justify-end space-x-3 border-t border-gray-200 rounded-b-lg flex-shrink-0">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={saving}
              className="px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:bg-gray-400"
            >
              {saving ? 'Saving...' : saveButtonText}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

